# NumPy

[**NumPy**](https://numpy.org/doc/stable/user/absolute_beginners.html) stands for **Numerical Python**, it is a popular, open-source library that's widely used in science and engineering. Let´s go through the basic concepts!

In [ ]:
print("hello")

In [ ]:
# import package
import numpy as np

# define 1D array
my_list = [1,2,3,4,5]
print(my_list)
my_arr = np.array(my_list)
my_arr

# define 2D array
my_list_nested = [[1,2,3],[4,5,6],[7,8,9]]
my_arr_2d = np.array(my_list_nested)
my_arr_2d

# define 3D array
my_list_3d = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
my_arr_3d = np.array(my_list_3d)
my_arr_3d

# # define odd array to demo error
# my_odd_list = [[1,2,3],[4,5]]
# arr_odd = np.array(my_odd_list)
# arr_odd

[1, 2, 3, 4, 5]


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

To see [details](https://numpy.org/doc/stable/user/absolute_beginners.html#how-do-you-know-the-shape-and-size-of-an-array) about your array, print the following properties:
  - `.ndim` to see the number of dimensions
  - `.shape` to see a tuple representing the numbers of "rows" and "columns"
  - `.size` to see the total number of elements in the array
  - `.dtype` to see the data type of the elements that make up the array

In [ ]:
# ndim for each dimension
my_arr_2d.ndim

# shape for each dimension
my_arr_2d.shape

# size for each dimension
my_arr_2d.size

# dtype for each dimension
my_arr_2d.dtype

dtype('int64')

## Subsetting and Slicing
#### [Indexing](https://numpy.org/doc/stable/user/basics.indexing.html) elements in a one-dimensional array
This works the same as with Python lists: simply specify the single index, or specify a range to slice a section. **Please note**: Even if you save the slice to a new variable, you have created a [**view**](https://numpy.org/doc/stable/glossary.html#term-view), _not_ a copy. A view is simply a reference to the original array. To explicitly [make a copy](https://numpy.org/doc/stable/reference/generated/numpy.copy.html), you must use `copy()`. 


In [ ]:
# create orig_arr
orig_list = [1,2,3,4,5,6,7]
orig_arr = np.array(orig_list)
orig_arr

#show indexing and slicing elements of orig_array
orig_arr[0]
orig_arr[3:]


array([4, 5, 6, 7])

In [22]:
# create orig_arr
print(orig_arr)

# assign subset of existing array to new variable
new_arr = orig_arr[:3]
new_arr

# change a value in the new array and print outputs
new_arr[:] = 100
print(new_arr)
print(orig_arr)

# --> creating a new variable from the original array, will still alter the original array


[1 2 3 4 5 6 7]
[100 100 100]
[100 100 100   4   5   6   7]


In [ ]:
orig_list = [1,2,3,4,5,6,7]
orig_arr = np.array(orig_list)
orig_arr

# make a copy of the same array subset using copy()
copied_arr = orig_arr[:3].copy() # this adds only the first 3 values or orig_arr to the copy
copied_arr

# change a value in the copied array and print outputs
copied_arr[:] = 2000
print(copied_arr)
print(orig_arr)


# --> creating a copy of the original array will prevent alterations to the original


[2000 2000 2000]
[1 2 3 4 5 6 7]


If you are ever unsure if your array is a copy or a view, you can check by printing the [`arr.base`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.base.html). A copy will return `None`, but a view will return the array that it is based from. 

In [ ]:
# check .base for each copy
print(copied_arr.base)
print(new_arr.base)


[100 100 100   4   5   6   7]


#### Indexing a **single item** in a multi-dimensional array
This is very much the same as targetting a single item in a regular nested Python list: chain indexes together to indicate the levels (negatives work the same way as with single indexing). There are two possible syntax, both achieve the same result.

In [33]:
# create 2d array
my_list_nested = [[1,2,3],[4,5,6],[7,8,9]]
my_arr_2d = np.array(my_list_nested)
print(my_arr_2d)

# target nested item in multi-d array with [][] syntax
my_arr_2d[1][0]

# show same indexes together in single [,]
my_arr_2d[2,1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


np.int64(8)

#### Select **multiple contiguous items**

- Rows are targetted in the first dimension: `arr[start:end, :]` will slice the section between the defined row indexes (all columns). 
- Columns are targetted in the second dimension: `arr[:, start:end]` will slice the section between the defined column indexes (all rows).

Leaving any values undefined assumes "remainder", eg. `arr[:,:]` will select the whole array!

In [35]:
# create 2d array
my_list_nested = [[1,2,3],[4,5,6],[7,8,9]]
my_arr_2d = np.array(my_list_nested)
print(my_arr_2d)


# target some contiguous sections
my_arr_2d[1:,1:]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

#### Select **multiple non-contiguous items**
To select non-contiguous items, you can instead give a list of comma-separated indexes: `arr[row:row,[col,col,col]]`.

In [37]:
# create 2d array
my_list_nested = [[1,2,3],[4,5,6],[7,8,9]]
my_arr_2d = np.array(my_list_nested)
print(my_arr_2d)


# target some non-contiguous rows or columns
my_arr_2d[1, [0,2]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4, 6])

## Algebraic Operations

Algebraic operations in NumPy apply element-wise. They don’t change the original array—store results in a new variable. You can also operate between arrays, but their shapes must match.

In [ ]:
# create 2d array
my_list_nested = [[1,2,3],[4,5,6],[7,8,9]]
my_arr_2d = np.array(my_list_nested)
print(my_arr_2d)

# arr * 2
multi = my_arr_2d * 2
multi

# arr squared


# arr + 2
added = my_arr_2d + 2
added

# arr * arr
squared = my_arr_2d * my_arr_2d
squared

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## Boolean Array

You can apply a comparison operator in the same way as an algebraic operator. This will return a [**boolean array**](https://www.askpython.com/python-modules/numpy/numpy-boolean-array) for whether each value passes the comparison or not. 

For a quick type check, you can also set `np.array(arrayname, dtype=bool)`, which will check every value for a [truthy/falsy](https://www.freecodecamp.org/news/truthy-and-falsy-values-in-python/) value and return appropriate booleans.

In [44]:
# define truthy/falsy boolean array with dtype=bool
# create 2d array
my_list_nested = [[1,0,3],[4,5,6],[7,9,0]]
my_arr_2d = np.array(my_list_nested)
print(my_arr_2d)

bool1 = np.array(my_arr_2d, dtype=bool)
bool1

# define boolean array with comparison operator > 5
bool2 = my_arr_2d > 5
bool2


[[1 0 3]
 [4 5 6]
 [7 9 0]]


array([[False, False, False],
       [False, False,  True],
       [ True,  True, False]])

## Functions

NumPy provides _many_ [statistical](https://numpy.org/doc/stable/reference/routines.statistics.html) and [mathematical](https://numpy.org/doc/stable/reference/routines.math.html) functions that can be applied to its arrays. Some of particular note include:
  - `.max()` shows max value of an array
  - `.min()` shows min value of an array
  - `.argmax()` shows index of max value in an array
  - `.argmin()` shows index of min value in an array
  - `.sum()` returns the sum of all elements in an array

  - `.mean()` shows mean of an array
  - `.std()` shows standard deviation of an array

In [49]:
# demo some suggested aggregation function
print(my_arr_2d)

my_arr_2d.std()


[[1 0 3]
 [4 5 6]
 [7 9 0]]


np.float64(2.997941680718231)

Functions to [.sort()](https://numpy.org/doc/stable/reference/routines.sort.html#sorting-searching-and-counting), [np.concatenate()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) multiple arrays, or [.transpose()](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html) (ie. swapping array axes) are also worth investigating.

In [ ]:
# demo sort array
import numpy as np

arr1 = [21,7,5,7,8,91]
arr2 = [34,0,89,12,23,2]

# demo sort array
arr1.sort()
arr1

#demo concatenate two arrays
np.concatenate((arr1,arr2))

# demo transpose 2d array
print(my_arr_2d) # before
my_arr_2d.transpose() # after

# Stack
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.vstack([v1, v2])
np.hstack([v1, v2])

[[1 0 3]
 [4 5 6]
 [7 9 0]]


array([1, 2, 3, 4, 5, 6])

## Basic Arrays

For convenience, NumPy also have a range of functions to [create a **basic array**](https://numpy.org/doc/stable/reference/routines.array-creation.html) (you will see us do this quite often in spikes to generate "dummy" data):
  - `np.zeros()` takes an integer to produce an1D array of zeros / `np.zeros(num1,num2)` creates a table
  - `np.ones()` does the same for ones
  - `np.full()` does the same for any given number / `np.full((3,4)8)` will define a table of 3 rows, 4 columns holding value 8
  - `np.arange()`takes a start (optional), an end and increment (optional)
  - `np.linspace()` enter start point, end point, and how many elements to be linearly generated between
  - `np.eye()` creates a 2D array of zeros with a diagonal of ones. Specify how many columns, and `k=n` indicates the diagonal index. 
  - `np.random.rand()` random values between 0-1 in given shape
  - `np.random.randint()` enter start, end and size for array of random integers

Some of these functions will also accept the keyword argument `dtype` to specify the data type if you don't want to use floats. 

In [ ]:
# create array of zeros / ones / full
np.zeros((5,5))
np.ones((5,5), dtype=int)
np.full((5,5),6)

# # # set some ranges
np.arange(10,21,2) # shws all even numbers between 10 and 20

# # linspace 0-1, 0-10 (num=100 for both) to demo difference
np.linspace(1,11,num=100)

# # random in one or two dimensions
np.random.rand(3,4)

# # # random  integers in one dimension
np.random.randint(1,100,20)

# # random itengers in two dimensions with defined size
np.random.randint(1, 20, size=(3, 3))



array([10, 12, 14, 16, 18, 20])

[**Reshaping**](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) or otherwise [manipulating](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) an existing array is sometimes required. You will need to make sure you have enough values to fit the new shape. If you don't know how many rows, you can enter `-1`. 

In [ ]:
# define random int array of 10
arr = np.random.randint(1,100,10)
arr

# reshape to (5,2)
arr.reshape(5,2)

# reshape with (-1,2)
arr.reshape(-1)
arr.reshape(-1,2)

# "-1 means: you figure out this dimension automatically based on the array size and the other dimension I provided."


array([[72, 87],
       [56, 28],
       [14, 51],
       [57,  9],
       [69, 54]], dtype=int32)

NumPy [official documentation](https://numpy.org/doc/stable/user/basics.html) is very thorough if you want to look deeper into any functionalities it provides. [W3Schools](https://www.w3schools.com/python/numpy/numpy_intro.asp) also have a great NumPy documentation that outlines basic use-cases with great examples. The library updates quite often though, so it can be some of their examples are a little bit outdated. Always refer back to the official documentation if you are unsure.